# CircleCI configuration file
version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0


jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout

      - run: 
          name: Lint code
          command: echo "Linting repository"

      - run: 
          name: Run unit tests
          command: echo "Running unit tests"

  continuous-delivery:
    executor: gcp-gcr/default

    environment:
        REPOSITORY: finance-complaint
        IMAGE_NAME: finance-complaint
        IMAGE_TAG: latest
        PROJECT_ID: industry-ready-finance
        GAR_LOCATION: asia-south1

    steps:
      - checkout
      - gcp-gcr/gcr-auth

      - gcp-gcr/build-image:
          image: orb-test
          no_output_timeout: 20m
          registry-url: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY

      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: $IMAGE_NAME:$IMAGE_TAG
          registry-url: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY

      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

      # - gcp-gcr/continuous-delivery:
      #     context: .
      #     image: $IMAGE_NAME:$IMAGE_TAG
      #     registry-url: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY
      #     setup-remote-docker: true
      #     use-docker-layer-caching: true

      # - setup_remote_docker: 
      #     version: 20.10.14
      #     docker_layer_caching: true

      # - run: 
      #     name: Build Docker 
      #     command: docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .

      # - run:
      #     name: Build Docker 
      #     command: docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .


  continuous-deployment:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - run: 
          name: Echo test
          command: echo "Linting repository"

  # post-actions:
  #   machine: true
  #   resource_class: ketangangal/machines
  #   steps:
  #     - run: 
  #         name: Echo test
  #         command: echo "Hi I'm on Runners!"

  
workflows:
  build-workflow:
    jobs:
      - continuous-integration

      - continuous-delivery:
          requires:
            - continuous-integration

      - Wait:
          type: approval
          requires:
          - continuous-delivery

      - continuous-deployment:
          requires:
            - continuous-integration
            - continuous-delivery
      
      # - continuous-deployment
      # - post-actions