version: 2.1

# orbs:
#   gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout

      - run: 
          name: Lint code
          command: echo "Linting repository"

      - run: 
          name: Run unit tests
          command: echo "Running unit tests"
  
  continuous-delivery:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - run:
            name: "echo an env var that is part of our project"
            command: |
              echo $Test # this env var must be set within the project


  continuous-deployment:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - run: 
          name: Echo test
          command: echo "Linting repository"

  
workflows:
  CICD:
    jobs:
      - continuous-integration

      - continuous-delivery:
          requires:
            - continuous-integration

      # - gcp-cli/install_and_initialize_cli:
      #     gcloud-service-key: $GCLOUD_SERVICE_KEY

      - Wait:
          type: approval
          requires:
          - continuous-delivery

      - continuous-deployment:
          requires:
            - continuous-integration
            - continuous-delivery
      
      # - continuous-deployment
      # - post-actions