# CircleCI configuration file
version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout

      - run: 
          name: Lint code
          command: echo "Linting repository"

      - run: 
          name: Run unit tests
          command: echo "Running unit tests"
  
  continuous-delivery:
    docker:
      - image: cimg/base:stable
    resource_class: medium

    environment:
        REPOSITORY: finance-complaint
        IMAGE_NAME: finance-complaint
        IMAGE_TAG: latest
        PROJECT_ID: industry-ready-finance
        GAR_LOCATION: asia-south1

    steps:
      - checkout
      - gcp-cli/install_and_initialize_cli:
          gcloud-service-key: ${GCLOUD_SERVICE_KEY}




  continuous-deployment:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - run: 
          name: Echo test
          command: echo "Linting repository"

  # post-actions:
  #   machine: true
  #   resource_class: ketangangal/machines
  #   steps:
  #     - run: 
  #         name: Echo test
  #         command: echo "Hi I'm on Runners!"

  
workflows:
  build-workflow:
    jobs:
      - continuous-integration

      - continuous-delivery:
          requires:
            - continuous-integration

      - Wait:
          type: approval
          requires:
          - continuous-delivery

      - continuous-deployment:
          requires:
            - continuous-integration
            - continuous-delivery
      
      # - continuous-deployment
      # - post-actions