# CircleCI configuration file
version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: ketangangal/machines
    steps:
      - run: 
          name: Echo test
          command: echo "Hi I'm on Runners!"